#!/usr/bin/env bash

set -euo pipefail

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "${HERE}/shared"

"${HERE}/sync-venv"

(cd "${SRC_PATH}/pyidp/tests" && "${VENV_PYTEST}" "$@")